"""SQLite driver. WAL: many concurrent readers, exactly one writer.

Connections are per-thread (sqlite3 objects are not thread-safe) so the
concurrency tests exercise real cross-connection contention, not a shared handle.
"""
from __future__ import annotations

import json
import sqlite3
import threading
import time
from typing import Optional, Sequence

from ..errors import NotFound, VersionConflict
from ..uri import parse, topic_prefix, glob_match
from .base import Entry, Grant

SCHEMA = """
CREATE TABLE IF NOT EXISTS entry (
  uri TEXT PRIMARY KEY, workspace TEXT NOT NULL, topic TEXT NOT NULL,
  kind TEXT NOT NULL, id TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1,
  schema_id TEXT, status TEXT NOT NULL DEFAULT 'accepted',
  body TEXT, artifact_uri TEXT, body_hash TEXT NOT NULL,
  digest TEXT NOT NULL, digest_generated INTEGER NOT NULL DEFAULT 0,
  bytes INTEGER NOT NULL, est_tokens INTEGER NOT NULL,
  producer TEXT NOT NULL, model TEXT, confidence REAL, sources TEXT,
  trust REAL NOT NULL DEFAULT 0,
  ttl_at INTEGER, pinned INTEGER NOT NULL DEFAULT 0,
  reads INTEGER NOT NULL DEFAULT 0, last_read_at INTEGER,
  created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_entry_scope   ON entry(workspace, topic, kind, status);
CREATE INDEX IF NOT EXISTS ix_entry_updated ON entry(workspace, updated_at DESC);

CREATE TABLE IF NOT EXISTS entry_history (
  uri TEXT NOT NULL, version INTEGER NOT NULL, body TEXT, artifact_uri TEXT,
  body_hash TEXT NOT NULL, digest TEXT, producer TEXT, status TEXT,
  sources TEXT, created_at INTEGER NOT NULL,
  PRIMARY KEY (uri, version)
);

CREATE TABLE IF NOT EXISTS link (
  src_uri TEXT NOT NULL, rel TEXT NOT NULL, dst_uri TEXT NOT NULL,
  weight REAL DEFAULT 1.0, created_at INTEGER NOT NULL,
  PRIMARY KEY (src_uri, rel, dst_uri)
);
CREATE INDEX IF NOT EXISTS ix_link_dst ON link(dst_uri, rel);

CREATE TABLE IF NOT EXISTS event (
  seq INTEGER PRIMARY KEY AUTOINCREMENT, ts INTEGER NOT NULL,
  workspace TEXT NOT NULL, topic TEXT NOT NULL, type TEXT NOT NULL,
  uri TEXT, actor TEXT, payload TEXT
);
CREATE INDEX IF NOT EXISTS ix_event_scope ON event(workspace, seq);

CREATE TABLE IF NOT EXISTS grant (
  token_hash TEXT PRIMARY KEY, agent_id TEXT NOT NULL, role TEXT NOT NULL,
  workspace TEXT NOT NULL, topic_globs TEXT NOT NULL, caps TEXT NOT NULL,
  issued_at INTEGER NOT NULL, expires_at INTEGER
);

CREATE VIRTUAL TABLE IF NOT EXISTS entry_fts USING fts5(
  uri UNINDEXED, digest, body_text, tokenize='porter'
);
"""

_COLS = ("uri workspace topic kind id version schema_id status body artifact_uri body_hash "
         "digest digest_generated bytes est_tokens producer model confidence sources trust "
         "reads last_read_at created_at updated_at").split()


def _now() -> int:
    return int(time.time())


def _row_to_entry(r: sqlite3.Row) -> Entry:
    return Entry(
        uri=r["uri"], workspace=r["workspace"], topic=r["topic"], kind=r["kind"], id=r["id"],
        version=r["version"], schema_id=r["schema_id"], status=r["status"], body=r["body"],
        artifact_uri=r["artifact_uri"], body_hash=r["body_hash"], digest=r["digest"],
        digest_generated=bool(r["digest_generated"]), bytes=r["bytes"],
        est_tokens=r["est_tokens"], producer=r["producer"], model=r["model"],
        confidence=r["confidence"], sources=json.loads(r["sources"] or "[]"),
        trust=r["trust"], reads=r["reads"], last_read_at=r["last_read_at"],
        created_at=r["created_at"], updated_at=r["updated_at"],
    )


class SQLiteStore:
    def __init__(self, path: str):
        self.path = path
        self._local = threading.local()
        self.init_schema()

    # ------------------------------------------------------------------ conn
    @property
    def conn(self) -> sqlite3.Connection:
        c = getattr(self._local, "conn", None)
        if c is None:
            c = sqlite3.connect(self.path, timeout=10.0, isolation_level=None)
            c.row_factory = sqlite3.Row
            c.execute("PRAGMA journal_mode=WAL")
            c.execute("PRAGMA synchronous=NORMAL")
            c.execute("PRAGMA busy_timeout=5000")
            c.execute("PRAGMA foreign_keys=ON")
            self._local.conn = c
        return c

    def init_schema(self) -> None:
        self.conn.executescript(SCHEMA)

    def close(self) -> None:
        c = getattr(self._local, "conn", None)
        if c is not None:
            c.close()
            self._local.conn = None

    # ---------------------------------------------------------------- entries
    def get(self, uri: str, version: Optional[int] = None) -> Optional[Entry]:
        if version is None:
            r = self.conn.execute("SELECT * FROM entry WHERE uri=?", (uri,)).fetchone()
            return _row_to_entry(r) if r else None
        cur = self.conn.execute("SELECT * FROM entry WHERE uri=? AND version=?", (uri, version))
        r = cur.fetchone()
        if r:
            return _row_to_entry(r)
        h = self.conn.execute(
            "SELECT * FROM entry_history WHERE uri=? AND version=?", (uri, version)).fetchone()
        if not h:
            return None
        cur_e = self.get(uri)
        if cur_e is None:
            return None
        cur_e.version, cur_e.body = version, h["body"]
        cur_e.artifact_uri, cur_e.body_hash = h["artifact_uri"], h["body_hash"]
        cur_e.digest, cur_e.status = h["digest"], h["status"]
        cur_e.sources = json.loads(h["sources"] or "[]")
        return cur_e

    def get_many(self, uris: Sequence[str]) -> list:
        if not uris:
            return []
        qs = ",".join("?" * len(uris))
        rows = self.conn.execute(f"SELECT * FROM entry WHERE uri IN ({qs})", tuple(uris)).fetchall()
        by = {r["uri"]: _row_to_entry(r) for r in rows}
        return [by[u] for u in uris if u in by]

    def put(self, e: Entry, expect_version: Optional[int]) -> Entry:
        c = self.conn
        try:
            c.execute("BEGIN IMMEDIATE")
            cur = c.execute("SELECT * FROM entry WHERE uri=?", (e.uri,)).fetchone()
            if cur is None:
                if expect_version not in (None, 0):
                    raise VersionConflict("entry does not exist", uri=e.uri,
                                          current_version=None, expected=expect_version)
                e.version, e.created_at = 1, _now()
            else:
                if expect_version is not None and expect_version != cur["version"]:
                    raise VersionConflict(
                        "entry was modified by another agent; re-read and merge",
                        uri=e.uri, current_version=cur["version"], expected=expect_version)
                c.execute(
                    "INSERT OR REPLACE INTO entry_history"
                    "(uri,version,body,artifact_uri,body_hash,digest,producer,status,sources,created_at)"
                    " VALUES (?,?,?,?,?,?,?,?,?,?)",
                    (cur["uri"], cur["version"], cur["body"], cur["artifact_uri"],
                     cur["body_hash"], cur["digest"], cur["producer"], cur["status"],
                     cur["sources"], cur["updated_at"]))
                e.version, e.created_at = cur["version"] + 1, cur["created_at"]
            e.updated_at = _now()
            c.execute(
                "INSERT OR REPLACE INTO entry (uri,workspace,topic,kind,id,version,schema_id,"
                "status,body,artifact_uri,body_hash,digest,digest_generated,bytes,est_tokens,"
                "producer,model,confidence,sources,trust,reads,last_read_at,created_at,updated_at)"
                " VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
                (e.uri, e.workspace, e.topic, e.kind, e.id, e.version, e.schema_id, e.status,
                 e.body, e.artifact_uri, e.body_hash, e.digest, int(e.digest_generated),
                 e.bytes, e.est_tokens, e.producer, e.model, e.confidence,
                 json.dumps(e.sources), e.trust,
                 cur["reads"] if cur else 0, cur["last_read_at"] if cur else None,
                 e.created_at, e.updated_at))
            c.execute("DELETE FROM entry_fts WHERE uri=?", (e.uri,))
            c.execute("INSERT INTO entry_fts (uri,digest,body_text) VALUES (?,?,?)",
                      (e.uri, e.digest, e.body or ""))
            c.execute("COMMIT")
            return e
        except Exception:
            try:
                c.execute("ROLLBACK")
            except sqlite3.Error:
                pass
            raise

    def query(self, workspace, topic_glob=None, kind=None, status=None,
              order="recency", limit=20) -> list:
        sql = "SELECT * FROM entry WHERE workspace=?"
        args = [workspace]
        if kind:
            sql += " AND kind=?"
            args.append(kind)
        if status:
            sql += " AND status=?"
            args.append(status)
        if topic_glob:
            pre = topic_prefix(topic_glob)
            if pre:
                sql += " AND topic LIKE ?"
                args.append(pre.split("/")[0] + "%")
        sql += {" recency": "", "recency": " ORDER BY updated_at DESC",
                "created": " ORDER BY created_at ASC",
                "topic": " ORDER BY topic, kind, id"}.get(order, " ORDER BY updated_at DESC")
        sql += " LIMIT ?"
        args.append(max(1, min(int(limit) * 4, 2000)))
        rows = [_row_to_entry(r) for r in self.conn.execute(sql, tuple(args)).fetchall()]
        if topic_glob:
            rows = [e for e in rows if glob_match(topic_glob, f"{e.topic}/{e.kind}/{e.id}")
                    or glob_match(topic_glob, e.topic)]
        return rows[:limit]

    def search(self, workspace: str, q: str, limit: int = 10) -> list:
        try:
            rows = self.conn.execute(
                "SELECT f.uri AS uri, bm25(entry_fts) AS score FROM entry_fts f "
                "JOIN entry e ON e.uri=f.uri WHERE entry_fts MATCH ? AND e.workspace=? "
                "ORDER BY score LIMIT ?", (q, workspace, limit)).fetchall()
        except sqlite3.OperationalError:
            return []
        return [(r["uri"], float(r["score"])) for r in rows]

    def history(self, uri: str) -> list:
        return [dict(r) for r in self.conn.execute(
            "SELECT version,digest,producer,status,created_at FROM entry_history "
            "WHERE uri=? ORDER BY version", (uri,)).fetchall()]

    def touch_reads(self, uris: Sequence[str]) -> None:
        if not uris:
            return
        qs = ",".join("?" * len(uris))
        self.conn.execute(
            f"UPDATE entry SET reads=reads+1, last_read_at=? WHERE uri IN ({qs})",
            (_now(), *uris))

    # ------------------------------------------------------------------ links
    def link(self, src: str, rel: str, dsts: Sequence[str]) -> int:
        n = 0
        for d in dsts:
            self.conn.execute(
                "INSERT OR IGNORE INTO link (src_uri,rel,dst_uri,created_at) VALUES (?,?,?,?)",
                (src, rel, d, _now()))
            n += 1
        return n

    def links_from(self, src: str) -> list:
        return [(r["rel"], r["dst_uri"]) for r in self.conn.execute(
            "SELECT rel,dst_uri FROM link WHERE src_uri=?", (src,)).fetchall()]

    def links_to(self, dst: str) -> list:
        return [(r["src_uri"], r["rel"]) for r in self.conn.execute(
            "SELECT src_uri,rel FROM link WHERE dst_uri=?", (dst,)).fetchall()]

    # ----------------------------------------------------------------- events
    def append_event(self, workspace, topic, type_, uri, actor, payload=None) -> int:
        cur = self.conn.execute(
            "INSERT INTO event (ts,workspace,topic,type,uri,actor,payload) VALUES (?,?,?,?,?,?,?)",
            (_now(), workspace, topic, type_, uri, actor,
             json.dumps(payload) if payload else None))
        return cur.lastrowid

    def events_since(self, workspace: str, cursor: int, limit: int = 100) -> list:
        return [dict(r) for r in self.conn.execute(
            "SELECT seq,ts,topic,type,uri,actor FROM event WHERE workspace=? AND seq>? "
            "ORDER BY seq LIMIT ?", (workspace, cursor, limit)).fetchall()]

    # ----------------------------------------------------------------- grants
    def put_grant(self, g: Grant) -> None:
        self.conn.execute(
            "INSERT OR REPLACE INTO grant "
            "(token_hash,agent_id,role,workspace,topic_globs,caps,issued_at,expires_at)"
            " VALUES (?,?,?,?,?,?,?,?)",
            (g.token_hash, g.agent_id, g.role, g.workspace, json.dumps(g.topic_globs),
             json.dumps(g.caps), g.issued_at, g.expires_at))

    def get_grant(self, token_hash: str) -> Optional[Grant]:
        r = self.conn.execute("SELECT * FROM grant WHERE token_hash=?", (token_hash,)).fetchone()
        if not r:
            return None
        return Grant(r["token_hash"], r["agent_id"], r["role"], r["workspace"],
                     json.loads(r["topic_globs"]), json.loads(r["caps"]),
                     r["issued_at"], r["expires_at"])

    def list_grants(self, workspace: str) -> list:
        return [dict(r) for r in self.conn.execute(
            "SELECT token_hash,agent_id,role,topic_globs,caps,expires_at FROM grant "
            "WHERE workspace=?", (workspace,)).fetchall()]

    def delete_grant(self, token_hash: str) -> bool:
        return self.conn.execute(
            "DELETE FROM grant WHERE token_hash=?", (token_hash,)).rowcount > 0

    # -------------------------------------------------------------------- ops
    def stats(self, workspace: str) -> dict:
        r = self.conn.execute(
            "SELECT COUNT(*) n, COALESCE(SUM(bytes),0) b, COALESCE(SUM(est_tokens),0) t "
            "FROM entry WHERE workspace=?", (workspace,)).fetchone()
        kinds = {k["kind"]: k["n"] for k in self.conn.execute(
            "SELECT kind, COUNT(*) n FROM entry WHERE workspace=? GROUP BY kind",
            (workspace,)).fetchall()}
        topics = {k["topic"]: k["n"] for k in self.conn.execute(
            "SELECT topic, COUNT(*) n FROM entry WHERE workspace=? GROUP BY topic",
            (workspace,)).fetchall()}
        ev = self.conn.execute(
            "SELECT COALESCE(MAX(seq),0) s FROM event WHERE workspace=?", (workspace,)).fetchone()
        return {"entries": r["n"], "bytes": r["b"], "est_tokens": r["t"],
                "kinds": kinds, "topics": topics, "cursor": ev["s"]}
